services:
  redis:
    image: redis:7-alpine
    container_name: dev_redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 5s
      timeout: 3s
      retries: 20
volumes:
  redisdata:
