http:
  middlewares:
    strip-user-prefix:
      stripPrefix:
        prefixes:
          - /api/users

  routers:
    # dashboard (dev only) -> http://localhost:8080
    traefik:
      rule: "PathPrefix(`/dashboard`) || PathPrefix(`/api/dashboard`)"
      service: api@internal
      entryPoints:
        - web

  services:
    # services are defined via labels in docker-compose
    # (this file can hold extras if needed)
