-- Example starter schema used by user-service
-- CREATE TABLE IF NOT EXISTS users (
--   id SERIAL PRIMARY KEY,
--   username TEXT UNIQUE NOT NULL,
--   email TEXT UNIQUE NOT NULL,
--   created_at TIMESTAMPTZ NOT NULL DEFAULT now()
-- );
